apiVersion: v1
description: A Confluence Server Helm chart for Kubernetes
home: https://praqma.com/
icon: https://wac-cdn.atlassian.com/dam/jcr:a22c9f02-b225-4e34-9f1d-e5ac0265e543/confluence_rgb_slate.png
maintainers:
- email: sami@praqma.com
  name: '@sami-alajrami'
- email: kaz@praqma.com
  name: '@KamranAzeem'
name: confluence
version: 0.4.2
