kind: PersistentVolume
apiVersion: v1
metadata:
  name: confluence-server-pv
  labels:
    product: atlassian-confluence
    type: server
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/confluence-server-pv"
