{{- if .Values.RBAC.Enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: confluence
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: confluence
subjects:
- kind: ServiceAccount
  name: confluence
  namespace: {{ .Release.Namespace }}
{{- end }}
