# Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "confluence-chart.labels" . | indent 4 }}

  annotations:
  {{- if .Values.PrometheusMetrics.Enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.PrometheusMetrics.Path  | quote }}
    prometheus.io/port: {{ .Values.Service.Port | quote }}
  {{- end }}
  {{- range $key, $value := .Values.Service.Annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

spec:
  ports:
    # port is what this service should serve on, and targetPort is the port in the container.
    - port: {{ .Values.Service.Port }}
      name: confluence-main
      targetPort: {{ .Values.Service.Port }}
      protocol: {{ .Values.Service.Protocol }}
    - port: 8888
      name: confluence-internal-connector
      targetPort: 8888
      protocol: TCP
    {{- if .Values.Datacenter.Enabled }}
    - port: 8091
      name: synchrony
      protocol: TCP
      targetPort: 8091
# four lines below added by mustafa for http connnection
    - port: 80
      name: confluence-main2
      targetPort: {{ .Values.Service.Port }}
      protocol: {{ .Values.Service.Protocol }}
  {{- end }}

{{- if .Values.Datacenter.Enabled }}
# below 3 lines are changed/added by mustafa
  #clusterIP: None
  type: LoadBalancer
  sessionAffinity: ClientIP
{{- else }}
  type: {{ .Values.Service.Type | default "ClusterIP" }}
{{- end }}

  selector:
    app: {{ .Release.Name }}
#####
